---
- hosts:
    team-004
  vars:
    ansible_user: sysop
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Copy Luc Sabourin Private SSH Key
      ansible.windows.win_copy:
        src: ~/devenv/sshkeys/gitlab/home/team-04/.ssh/team-04
        dest: C:\Users\team-04\.ssh\id_rsa
    - name: Copy Luc Sabourin Public SSH Key
      ansible.windows.win_copy:
        src: ~/devenv/sshkeys/gitlab/home/team-04/.ssh/id_rsa.pub
        dest: C:\Users\team-04\.ssh\id_rsa.pub
