---
- hosts:
    team-002
  vars:
    ansible_user: team-02
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install OpenJDK 17.0.2
      win_chocolatey:
        name: oraclejdk
        state: present
    - name: Install Maven 3.8.5
      win_chocolatey:
        name: maven
        state: present
    - name: IntelliJ IDEA Community
      win_chocolatey:
        name: intellijidea-community
        state: present
