---
- name: Setup Java 11 Headless Runtime
  hosts: ckan-01
  become: yes
  gather_facts: true
  tasks:
    - name: Install Java 11 Headless Runtime
      apt:
        name: openjdk-11-jre-headless
        state: present
    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-1.11.0-openjdk-amd64"'
        regex: '^JAVA_HOME='
        state: present
