    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-1.11.0-openjdk-amd64"'
        search_string: 'JAVA_HOME'
        state: present
