---
- hosts:
    team-002
  vars:
    ansible_user: sysop
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Uninstall Git For Windows
      win_chocolatey:
        name: git
        state: absent
