---
- name: Distribute Public Keys to CKAN server
  hosts: ckan-01
  become: yes
  gather_facts: true
  tasks:
    - name: Add Ansible Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/.ssh/id_rsa.pub') }}"
    - name: Add team-01 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-01/.ssh/id_rsa.pub') }}"
    - name: Add team-02 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-02/.ssh/id_rsa.pub') }}"
    - name: Add team-03 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-03/.ssh/id_rsa.pub') }}"
    - name: Add team-04 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-04/.ssh/id_rsa.pub') }}"
    - name: Add team-05 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-05/.ssh/id_rsa.pub') }}"
    - name: Add team-01 Public Key to Sysop User Authorized Keys
      ansible.posix.authorized_key:
        user: sysop
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-01/.ssh/id_rsa.pub') }}"
    - name: Add team-02 Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: sysop
        state: present
        key: "{{ lookup('file', '/home/sysop/devenv/sshkeys/gitlab/home/team-02/.ssh/id_rsa.pub') }}"
