---
- name: Setup CKAN Python Required Modules
  hosts: machines
  become: yes
  gather_facts: true
  tasks:
    - name: Install Python3 Pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: Install Python3 dev
      apt:
        name: python3-dev
        state: present
    - name: Install Python3 venv
      apt:
        name: python3-venv
        state: present
    - name: Install libpq-dev
      apt:
        name: libpq-dev
        state: present
