---
- name: Setup ckan User
  hosts: machines
  become: yes
  gather_facts: true
  tasks:
    - name: Setup CKAN User
      user:
        name: ckan
        comment: CKAN,,,,ckan
        state: present
        create_home: yes
        home: /home/ckan
        shell: /usr/bin/bash
        skeleton: /etc/skel
        system: no
        generate_ssh_key: yes
    - name: Add Ansible Public Key to CKAN User Authorized Keys
      ansible.posix.authorized_key:
        user: ckan
        state: present
        key: "{{ lookup('file', '/home/sysop/.ssh/id_rsa.pub') }}"
    - name: Clone Dotfiles for ckan User
      git:
      become: yes
      become_user: ckan
      args:
        repo: 'https://github.com/Waiver-Wire-Addict/dotfiles.git'
        dest: ~/dotfiles
    - name: Install ckan Dotfiles
      command:
      become: yes
      become_user: ckan
      args:
        cmd: ./install-regular-user.sh
        chdir: ~/dotfiles
